-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 19:33:03 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema publisher
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema publisher
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `publisher` DEFAULT CHARACTER SET utf8 ;
USE `publisher` ;

-- -----------------------------------------------------
-- Table `publisher`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publisher`.`subscriptions` (
  `subscriptions_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `topic` VARCHAR(100) NOT NULL,
  `url` VARCHAR(2083) NOT NULL,
  PRIMARY KEY (`subscriptions_id`),
  UNIQUE INDEX `idx_topic` (`topic` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `publisher`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publisher`.`messages` (
  `messages_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `subscriptions_id` INT UNSIGNED NOT NULL,
  `message` MEDIUMTEXT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`messages_id`),
  INDEX `fk_messages_subscriptions_id_idx` (`subscriptions_id` ASC) VISIBLE,
  CONSTRAINT `fk_messages_subscriptions_id`
    FOREIGN KEY (`subscriptions_id`)
    REFERENCES `publisher`.`subscriptions` (`subscriptions_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
